{
 "title": "Ohm Windows Desktop",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE app = 'ohm'"
   },
   {
    "name": "hdd",
    "query": "SHOW TAG VALUES FROM \"Data\" WITH KEY = \"hw_instance\" WHERE app = 'ohm' AND hardware_type = 'HDD' AND host =~ /^$instance$/"
   },
   {
    "name": "network",
    "query": "SHOW TAG VALUES FROM \"Throughput\" WITH KEY = \"hardware\" WHERE app = 'ohm' AND hardware_type = 'NIC' AND host =~ /^$instance$/"
   },
   {
    "name": "cpu",
    "query": "SHOW TAG VALUES FROM \"Load\" WITH KEY = \"hardware\" WHERE app = 'ohm' AND hardware_type = 'CPU' AND host =~ /^$instance$/"
   },
   {
    "name": "gpu",
    "query": "SHOW TAG VALUES WITH KEY = \"hw_instance\" WHERE app = 'ohm' AND (hardware_type = 'GpuNvidia' OR hardware_type = 'GpuAti') AND host =~ /^$instance$/"
   }
  ]
 },
 "panels": [
  { "title": "Current Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'CPU Total' AND \"hardware_type\" = 'CPU' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Memory' AND \"hardware\" = 'Total Memory' AND \"hardware_type\" = 'RAM' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Max Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Total Activity' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Max Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Used Space' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Read' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Written' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND $timeFilter GROUP BY \"hardware\", \"sensor\", \"hw_instance\""
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Downloaded' AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Uploaded' AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Disk Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "GPU Compute",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'GPU Core' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'GPU Core' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'GPU Memory Used' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'GPU Memory Used' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Max Fan",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"value\") FROM \"Control\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Component Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Power\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'CPU' AND \"sensor\" =~ /.*Package/ AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Power\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND (\"hardware_type\" = 'GpuNvidia' OR \"hardware_type\" = 'GpuAti') AND $timeFilter GROUP BY time($__interval), \"hardware\", \"sensor\" fill(null)"
    }
   ]
  },
  {
   "title": "Disk Media Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"SmallData\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Media Errors' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  { "title": "CPU: $cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "cpu" },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" != 'CPU Total' AND \"hardware_type\" = 'CPU' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "{{_sensor}}"
    }
   ]
  },
  {
   "title": "Wattage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Power\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'CPU' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Temperature\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'CPU' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "{{_sensor}}"
    }
   ]
  },
  {
   "title": "Volts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Voltage\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'CPU' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "{{_sensor}}"
    }
   ]
  },
  {
   "title": "Frequencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Clock\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'CPU' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "{{_sensor}}"
    }
   ]
  },
  { "title": "GPU: $gpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "repeat": "gpu" },
  {
   "title": "GPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Frequencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Clock\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Clock\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Wattage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Power\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Power\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Fan\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval), \"hw_instance\" fill(null)",
     "alias": "Fan"
    },
    {
     "query": "SELECT max(\"value\") FROM \"Fan\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "alias": "High RPM"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Fan\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval), \"hw_instance\" fill(null)",
     "alias": "Fan"
    },
    {
     "query": "SELECT max(\"value\") FROM \"Fan\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "alias": "High RPM"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Temperature\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Temperature\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'GpuNvidia' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$gpu' AND \"hardware_type\" = 'GpuAti' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  { "title": "Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Drives",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "query": "SELECT last(\"value\") FROM \"Temperature\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY \"hw_instance\""
    },
    {
     "query": "SELECT last(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Read' AND \"hardware_type\" = 'HDD' AND $timeFilter"
    },
    {
     "query": "SELECT last(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Written' AND \"hardware_type\" = 'HDD' AND $timeFilter"
    },
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Read' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY \"hw_instance\""
    },
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Written' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY \"hw_instance\""
    },
    {
     "query": "SELECT last(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Used Space' AND \"hardware_type\" = 'HDD' AND $timeFilter"
    },
    {
     "query": "SELECT last(\"value\") FROM \"SmallData\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Power Cycles' AND \"hardware_type\" = 'HDD' AND $timeFilter"
    },
    {
     "query": "SELECT last(\"value\") FROM \"SmallData\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Media Errors' AND \"hardware_type\" = 'HDD' AND $timeFilter"
    }
   ]
  },
  { "title": "Drive: $hdd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }, "repeat": "hdd" },
  {
   "title": "$hdd Factors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"SmallData\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$hdd' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Temperature\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$hdd' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"sensor\", \"hw_instance\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Disk Activity Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$hdd' AND \"sensor\" = 'Total Activity' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"hw_instance\" fill(null)",
     "alias": "Total"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$hdd' AND \"sensor\" = 'Write Activity' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"hw_instance\" fill(null)",
     "alias": "Write"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$hdd' AND \"sensor\" = 'Read Rate' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"hw_instance\" fill(null)",
     "alias": "Read"
    },
    {
     "query": "SELECT -1 * mean(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hw_instance\" = '$hdd' AND \"sensor\" = 'Write Rate' AND \"hardware_type\" = 'HDD' AND $timeFilter GROUP BY time($__interval), \"hw_instance\" fill(null)",
     "alias": "Write"
    }
   ]
  },
  { "title": "Motherboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Temperature\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'SuperIO' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Fan\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'SuperIO' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"Fan\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'SuperIO' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "High RPM"
    }
   ]
  },
  {
   "title": "Volts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 123 },
   "repeat": "volts",
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Voltage\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'SuperIO' AND $timeFilter GROUP BY time($__interval), \"sensor\" fill(null)",
     "alias": "$tag_sensor"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Network Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 133 },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Downloaded' AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY \"hardware\""
    },
    {
     "query": "SELECT sum(\"value\") FROM \"Data\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"sensor\" = 'Data Uploaded' AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY \"hardware\""
    },
    {
     "query": "SELECT last(\"value\") FROM \"Load\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware_type\" = 'NIC' AND $timeFilter"
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "repeat": "network",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware\" =~ /^$network$/ AND \"sensor\" = 'Download Speed' AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY time($__interval), \"hardware\" fill(null)",
     "alias": "Download"
    },
    {
     "query": "SELECT -1 * mean(\"value\") FROM \"Throughput\" WHERE app = 'ohm' AND \"host\" =~ /^$instance$/ AND \"hardware\" =~ /^$network$/ AND \"sensor\" = 'Upload Speed' AND \"hardware_type\" = 'NIC' AND $timeFilter GROUP BY time($__interval), \"hardware\" fill(null)",
     "alias": "Upload"
    }
   ]
  }
 ]
}