{
 "title": "ohm-timescale",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "SELECT DISTINCT(host) FROM ohm_stats WHERE $__timeFilter(time) "
   },
   {
    "name": "power",
    "query": "SELECT DISTINCT(hardware_type) FROM ohm_stats WHERE $__timeFilter(time) AND sensor_type = 'Power'"
   },
   {
    "name": "temperature",
    "query": "SELECT DISTINCT(hardware_type) FROM ohm_stats WHERE $__timeFilter(time) AND sensor_type = 'Temperature'"
   },
   {
    "name": "volt",
    "query": "SELECT DISTINCT(hardware_type) FROM ohm_stats WHERE $__timeFilter(time) AND sensor_type = 'Voltage'"
   },
   {
    "name": "network",
    "query": "SELECT DISTINCT(hardware) FROM ohm_stats WHERE $__timeFilter(time) AND hardware_type = 'NIC'"
   },
   {
    "name": "fan",
    "query": "SELECT DISTINCT(hardware_type) FROM ohm_stats WHERE $__timeFilter(time) AND sensor_type = 'Fan'"
   },
   {
    "name": "control",
    "query": "SELECT DISTINCT(hardware_type) FROM ohm_stats WHERE $__timeFilter(time) AND sensor_type = 'Control'"
   },
   {
    "name": "hertz",
    "query": "SELECT DISTINCT(hardware_type) FROM ohm_stats WHERE $__timeFilter(time) AND sensor_type = 'Clock'"
   }
  ]
 },
 "panels": [
  { "title": "Load Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'CPU' AND\n  sensor_type = 'Load' AND\n  sensor = 'CPU Total'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'RAM' AND\n  sensor_type = 'Load'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'GpuNvidia' AND\n  sensor_type = 'Load'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'GpuAti' AND\n  sensor_type = 'Load'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'HDD' AND\n  sensor_type = 'Load'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Load Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'CPU' AND\n  sensor_type = 'Load' AND\n  sensor != 'CPU Total'\nGROUP BY 1, sensor,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'GpuNvidia' AND\n  sensor_type = 'Load'\nGROUP BY 1, sensor,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'GpuAti' AND\n  sensor_type = 'Load'\nGROUP BY 1, sensor,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'RAM' AND\n  sensor_type = 'Data'\nGROUP BY 1, sensor,2\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'GpuNvidia' AND\n  sensor_type = 'SmallData'\nGROUP BY 1, sensor,2\nORDER BY 1,2"
      },
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value) AS \"sensor_index\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = 'GpuAti' AND\n  sensor_type = 'SmallData'\nGROUP BY 1, sensor,2\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  { "title": "Watts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$power Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "power",
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value)\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  sensor_type = 'Power' AND\n  hardware_type = $power\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$temperature Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "repeat": "temperature",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value)\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  sensor_type = 'Temperature' AND\n  hardware_type = $temperature\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Volts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$volt Volts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "repeat": "volt",
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value)\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  sensor_type = 'Voltage' AND\n  hardware_type = $volt\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Network Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "repeat": "network",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value)\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware = $network AND\n  hardware_type = 'NIC' AND\n  sensor = 'Download Speed'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value)\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware = $network AND\n  hardware_type = 'NIC' AND\n  sensor = 'Upload Speed'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Fan RPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "$fan Fan RPM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "repeat": "fan",
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value)\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = $fan AND\n  sensor_type = 'Fan'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "$control Fan RPM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "repeat": "control",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sensor AS metric,\n  avg(value)\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = $control AND\n  sensor_type = 'Control'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Frequencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "$hertz Frequencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "repeat": "hertz",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  sensor AS metric,\n  value * 1000000 AS \"value * 1000000\"\nFROM ohm_stats\nWHERE\n  $__timeFilter(\"time\") AND\n  host = '$instance' AND\n  hardware_type = $hertz AND\n  sensor_type = 'Clock'\nORDER BY 1,2"
    }
   ]
  }
 ]
}