{
 "title": "ohm-graphite",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": "tag_values(host, app=ohm)" },
   {
    "name": "power",
    "query": "tag_values(hardware_type, app=ohm, sensor_type=Power)"
   },
   {
    "name": "temperature",
    "query": "tag_values(hardware_type, app=ohm, sensor_type=Temperature)"
   },
   {
    "name": "volts",
    "query": "tag_values(hardware_type, app=ohm, sensor_type=Voltage)"
   },
   {
    "name": "network",
    "query": "tag_values(hardware, app=ohm, hardware_type=NIC)"
   },
   {
    "name": "fan",
    "query": "tag_values(hardware_type, app=ohm, sensor_type=Fan)"
   },
   {
    "name": "control",
    "query": "tag_values(hardware_type, app=ohm, sensor_type=Control)"
   },
   {
    "name": "hertz",
    "query": "tag_values(hardware_type, app=ohm, sensor_type=Clock)"
   }
  ]
 },
 "panels": [
  { "title": "Load Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "seriesByTag('host=$instance', 'sensor_type=Load', 'hardware_type=CPU', 'app=ohm', 'raw_name=CPU-Total')"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=RAM', 'sensor_type=Load'), 'raw_name')"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 1 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=GpuNvidia', 'sensor_type=Load'), 'raw_name')"
    },
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=GpuAti', 'sensor_type=Load'), 'raw_name')"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 1 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=HDD', 'sensor_type=Load'), 'raw_name')"
    }
   ]
  },
  { "title": "Load Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'sensor_type=Load', 'hardware_type=CPU', 'host=$instance'), 'raw_name')"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'sensor_type=Load', 'hardware_type=GpuNvidia', 'host=$instance'), 'raw_name')"
    },
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'sensor_type=Load', 'host=$instance', 'hardware_type=GpuAti'), 'raw_name')"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('host=$instance', 'app=ohm', 'hardware_type=RAM', 'sensor_type=Data'), 'raw_name')"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "target": "aliasByTags(seriesByTag('host=$instance', 'app=ohm', 'hardware_type=GpuNvidia', 'sensor_type=SmallData'), 'raw_name')"
      },
      {
       "target": "aliasByTags(seriesByTag('host=$instance', 'app=ohm', 'hardware_type=GpuAti', 'sensor_type=SmallData'), 'raw_name')"
      }
     ]
    }
   ]
  },
  { "title": "Watts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$power Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "power",
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=$power', 'sensor_type=Power'), 'raw_name')"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$temperature Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "repeat": "temperature",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=$temperature', 'sensor_type=Temperature'), 'raw_name')"
    }
   ]
  },
  { "title": "Volts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$volts Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "repeat": "volts",
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=$volts', 'sensor_type=Voltage'), 'raw_name')"
    }
   ]
  },
  { "title": "Network Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "repeat": "network",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(seriesByTag('app=ohm', 'host=$instance', 'hardware=$network', 'raw_name=Download-Speed'), 'Download')"
    },
    {
     "target": "alias(seriesByTag('app=ohm', 'host=$instance', 'hardware=$network', 'raw_name=Upload-Speed'), 'Upload')"
    }
   ]
  },
  { "title": "Fan RPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "$fan Fan RPM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "repeat": "fan",
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=$fan', 'sensor_type=Fan'), 'raw_name')"
    }
   ]
  },
  { "title": "Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "$control Control",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "repeat": "control",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'hardware_type=$control', 'sensor_type=Control'), 'raw_name')"
    }
   ]
  },
  { "title": "Frequencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "$hertz Frequencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "repeat": "hertz",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('app=ohm', 'host=$instance', 'sensor_type=Clock', 'hardware_type=$hertz'), 'raw_name')"
    }
   ]
  }
 ]
}