{
 "title": "Ohm",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cpu Utiliziation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Total" }
     ]
    }
   ]
  },
  {
   "title": "GPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Core" }
     ]
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Ram Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Used Memory" }
     ]
    }
   ]
  },
  {
   "title": "C:",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Used Space" },
      { "condition": "AND", "key": "hardware", "operator": "=", "value": "Generic Hard Disk" }
     ]
    }
   ]
  },
  {
   "title": "D:",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Used Space" },
      { "condition": "AND", "key": "hardware", "operator": "=", "value": "Samsung SSD 840 EVO 250GB" }
     ]
    }
   ]
  },
  {
   "title": "FAN 1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Control",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Fan Control #1" }
     ]
    }
   ]
  },
  {
   "title": "GPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Video Engine",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Video Engine" }
     ]
    },
    {
     "alias": "Core",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Core" }
     ]
    },
    {
     "alias": "Memory",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Memory" }
     ]
    },
    {
     "alias": "Memory Controller",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Memory Controller" }
     ]
    }
   ]
  },
  {
   "title": "Clock Speed GPU/CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "mhz" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Clock",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #1" }
     ]
    },
    {
     "alias": "GPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Clock",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Core" }
     ]
    },
    {
     "alias": "Shader",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Clock",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Shader" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Package",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Total" }
     ]
    },
    {
     "alias": "CPU Core 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #1" }
     ]
    },
    {
     "alias": "CPU Core 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #2" }
     ]
    },
    {
     "alias": "CPU Core 3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #3" }
     ]
    },
    {
     "alias": "CPU Core 4",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #4" }
     ]
    },
    {
     "alias": "CPU Core 5",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #5" }
     ]
    },
    {
     "alias": "CPU Core 6",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #6" }
     ]
    },
    {
     "alias": "CPU Core 6",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Memory" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "CPU Package",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Package" }
     ]
    },
    {
     "alias": "Nvidea",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=", "value": "/nvidiagpu/0/temperature/0" }
     ]
    },
    {
     "alias": "CPU Core 1",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #1" }
     ]
    },
    {
     "alias": "CPU Core 2",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #2" }
     ]
    },
    {
     "alias": "CPU Core 3",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #3" }
     ]
    },
    {
     "alias": "CPU Core 4",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #4" }
     ]
    },
    {
     "alias": "CPU Core 5",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #5" }
     ]
    },
    {
     "alias": "CPU Core 6",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #6" }
     ]
    },
    {
     "alias": "CPU Core 6",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Core #6" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Written",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "SSD Sata",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hardware", "operator": "=", "value": "Samsung SSD 840 EVO 250GB" }
     ]
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "CPU Package",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Package" }
     ]
    },
    {
     "alias": "CPU DRAM",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU DRAM" }
     ]
    },
    {
     "alias": "CPU Graphics",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Graphics" }
     ]
    },
    {
     "alias": "CPU Cores",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU Cores" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Used Memory" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Available Memory" }
     ]
    }
   ]
  },
  {
   "title": "SSD/HDD Used %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "SSD M.2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hardware", "operator": "=", "value": "Generic Hard Disk" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "Used Space" }
     ]
    },
    {
     "alias": "SSD SATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hardware", "operator": "=", "value": "Samsung SSD 840 EVO 250GB" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "Used Space" }
     ]
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "SmallData",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Memory Used" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "SmallData",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "GPU Memory Free" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "VCORE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "CPU VCore" }
     ]
    },
    {
     "alias": "Voltage 12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Voltage #12" }
     ]
    },
    {
     "alias": "Voltage 15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "Voltage #15" }
     ]
    }
   ]
  }
 ]
}